name: library_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  flutter_lints: ^2.0.0

flutter_intl:
  enabled: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

